name: Pancakes
main: me.Un1ted.Pancakes.Pancakes
version: 0.0.1
authors: [Un1ted4rmy, computerwizjared]
commands:
  punish:
   description: Jared's command
  db:
   description: Handles database interactions and dataflow.
  lovely:
   description: Custom easter egg for Lovely_013.